name: Dart (test)
'on':
  push:
    branches:
      - andersonbelli-patch-2
      - develop
      - master
env:
  QA: qa
  STAGING: staging
  DEV: develop
  MY_ENV_VAR: '${{ github.ref_name == ''develop'' }}'
  CURRENT_ENV: '${{ github.ref_name }}'
  PROJECT_ID: 'accuwriter-${{ github.ref_name }}'
  TARGET: 'lib/main_${{ github.ref_name }}.dart'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-cond@v1
        id: checkenv
        continue-on-error: true
        with:
          cond: '${{ github.ref_name == ''develop'' }}'
          if_true: $( echo 'my_dev_true' >> $CURRENT_ENV )
          if_false: $( echo 'my_dev_false' >> $CURRENT_ENV )
      - name: github.event.head_commit echo
        run: 'echo github_head_commit -> "${{ github.event.head_commit.message }}"'
      - name: Truncate String
        uses: 2428392/gh-truncate-string-action@v1.2.0
        id: truncatedString
        with:
          stringToTruncate: ${{ github.event.head_commit.message }}
          maxLength: 60
      - name: Truncate String echo
        run: 'echo truncatestring -> "${{ steps.truncatedString.outputs.string }}"'
      - name: aaaaaa
        run: 'echo -------------'
      - name: Use conditional value - checkenv
        run: 'echo checkenv -> "${{ steps.checkenv.outputs.value }}"'
        continue-on-error: true
      - name: "É DEV? ${{ github.ref_name }} == 'develop'"
        run: 'echo TRUE!!!!!'
        continue-on-error: true
        if: github.ref_name == 'develop'
      - name: "nao É DEV? ${{ github.ref_name }} == 'qa'"
        run: 'echo FALSE!!!!!'
        continue-on-error: true
        if: github.ref_name == 'qa'
      - name: Use conditional value
        continue-on-error: true
        run: |
          echo env.CURRENT_ENV
          echo ${{ env.CURRENT_ENV }}
          echo env.MY_ENV_VAR
          echo ${{ env.MY_ENV_VAR }}
          echo github.ref
          echo ${{ github.ref }}
          echo github.ref_name
          echo ${{ github.ref_name }}
          current_env=${{ env.MY_ENV_VAR }}
          if [[ ${{ github.ref_name }} == develop ]]; then
            echo "current_env=$(${{ env.DEV }})" >> $MY_ENV_VAR
            echo "delopinho1" >> $MY_ENV_VAR
            echo "echo delopinho2" >> $MY_ENV_VAR
            echo "env.MY_ENV_VAR - $MY_ENV_VAR - ${{ env.MY_ENV_VAR }}"
            echo "current env is DEV? ${current_env}"
            echo "env.DEV ${{ env.DEV }}"
            echo "env.MY_ENV_VAR ${{ env.MY_ENV_VAR }}"
            echo "env.MY_ENV_VAR >> ${{ env.MY_ENV_VAR }}"
            echo "aaaa ${{ env.MY_ENV_VAR }}"
            echo "bbbb ${MY_ENV_VAR}"
            $MY_ENV_VAR = "my_develop_var"
            MY_ENV_VAR = "my_develop_var"
            echo "cccc ${MY_ENV_VAR}"
          elif [[ ${{ github.ref_name }} == qa ]]; then
            echo "current_env=$(${{ env.QA }})" >> $MY_ENV_VAR
            echo "current env is QA? ${current_env} - $MY_ENV_VAR"
            echo "env.QA ${{ env.QA }}"
          else
            echo "There is no github tag reference, skipping"
            echo "What is the current env? ${current_env} - $MY_ENV_VAR"
            echo "env.CURRENT_ENV ${{ env.CURRENT_ENV }}"
            echo "CURRENT_ENV -> $CURRENT_ENV"
          fi
      - name: Select environment
        continue-on-error: true
        id: select-environment
        run: |
          if [ "${{ github.ref_name }}" == "develop" ]; then
            echo "develop"
            echo "selected-stage=qa" >> "$GITHUB_OUTPUT"
            echo "GITHUB_OUTPUT -> $GITHUB_OUTPUT"
          elif [ "${{ github.ref_name }}" == "qa" ]; then
            echo "qa"
            echo "selected-stage=qa" >> "$GITHUB_OUTPUT"
            echo "GITHUB_OUTPUT -> $GITHUB_OUTPUT"
          else
            echo "test"
            echo "selected-stage=test" >> "$GITHUB_OUTPUT"
          fi
          echo "GITHUB_OUTPUT -==-> $GITHUB_OUTPUT"
                
      - name: Use conditional value - select-environment
        continue-on-error: true
        run: 'echo "${{ steps.select-environment.outputs.select-environment }}"'
      - name: >-
          Checkout ${{ github.head_ref }} - ref_name-> ${{ github.ref_name }} - ${{
          github.event.pull_request.base.ref }}
        continue-on-error: true
        env:
          PROJECT_ID2: 'accuwriter-${{ github.event.pull_request.base.ref }}'
          TEST_VAR3: 'lib/main\_${{ env.CURRENT_ENV }}'
          TEST_VAR4: 'lib/asd_${{ env.CURRENT_ENV }}'
          TEST_VAR5: 'lib/main_${{ env.CURRENT_ENV }}'
        run: >-
          echo 'Base_REF ${{ github.base_ref }} {TARGET} ${{ env.TARGET }}
          {TEST_VAR3} ${TEST_VAR3} TEST_VAR4 $TEST_VAR4 TEST_VAR5 $TEST_VAR5
          PROJECT_ID2 ${PROJECT_ID2}'
      - name: Checkout PROJECT_ID1
        env:
          PROJECT_ID1: 'accuwriter-${{ github.event.pull_request.base.ref }}'
        run: echo $PROJECT_ID1
        if: false
      - name: Checkout PROJECT_ID
        if: false
        run: echo $PROJECT_ID
      - name: Checkout PROJECT_ID
        if: false
        run: echo 'PROJECT_ID_$PROJECT_ID'
      - name: Checkout TARGET env
        if: false
        env:
          TARGET1: 'lib/main_${{ github.base_ref }}'
        run: echo $TARGET1
      - name: Checkout TARGET
        if: false
        run: 'echo ''lib/main_${{ env.TARGET }}'''
      - name: Flutter
        if: false
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.x
          channel: stable
          cache: true
      - name: Web Build
        if: false
        run: >-
          flutter build web --dart-define --target ${{ env.TARGET }}
          --no-tree-shake-icons
