name: Dart (test)
'on':
  push:
    branches:
      - andersonbelli-patch-2
      - develop
      - master
env:
  QA: qa
  STAGING: staging
  DEV: develop
  MY_ENV_VAR: '${{ github.ref_name == ''develop'' }}'
  CURRENT_ENV: '${{ github.ref_name }}'
  PROJECT_ID: 'accuwriter-${{ github.ref_name }}'
  TARGET: 'lib/main_${{ github.ref_name }}.dart'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-cond@v1
        id: checkenv
        continue-on-error: true
        with:
          cond: '${{ github.ref_name == ''develop'' }}'
          if_true: $( echo 'my_dev_true' >> $CURRENT_ENV )
          if_false: $( echo 'my_dev_false' >> $CURRENT_ENV )
      - name: Truncate String
        id: truncate
        run: |
          const str = '${{ github.event.head_commit.message }}';
          const truncatedStr = str.length > 30 ? str.substring(0, 30) : str;
          console.log(truncatedStr);
          echo "::set-output name=truncated_string::${truncatedStr}"

      - name: Use Truncated String
        run: |
          echo "Truncated String: ${{ steps.truncate.outputs.truncated_string }}"
        
