name: Dart (test)
'on':
  push:
    branches:
      - develop
      - master
env:
  QA: qa
  STAGING: staging
  DEV: dev
  MY_ENV_VAR: '${{ github.ref_name == ''dev'' }}'
  CURRENT_ENV: '${{ github.ref_name }}'
  PROJECT_ID: 'accuwriter-${{ github.ref_name }}'
  TARGET: 'lib/main_${{ github.ref_name }}.dart'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-cond@v1
        id: check_env
        with:
          cond: '${{ github.ref_name == ''dev'' }}'
          if_true: $CURRENT_ENV
          if_false: value for non pull request event
      - name: Use conditional value
        run: 'echo "${{ steps.condval.outputs.value }}"'
      - name: Use conditional value
        run: |
          ls
          echo env.CURRENT_ENV
          echo ${{ env.CURRENT_ENV }}
          echo env.MY_ENV_VAR
          echo ${{ env.MY_ENV_VAR }}
          echo github.ref
          echo ${{ github.ref }}
          echo github.ref_name
          echo ${{ github.ref_name }}
          current_env=${{ env.MY_ENV_VAR }}
          if [[ ${{ github.ref_name }} == dev ]]; then
            echo "current_env=$(${{ env.DEV }})" >> $MY_ENV_VAR
            echo "current env is DEV? ${current_env}"
            echo "env.DEV ${{ env.DEV }}"
          elif [[ ${{ github.ref_name }} == qa ]]; then
            echo "current_env=$(${{ env.QA }})" >> $MY_ENV_VAR
            echo "current env is QA? ${current_env} - $MY_ENV_VAR"
            echo "env.QA ${{ env.QA }}"
          else
            echo "There is no github tag reference, skipping"
            echo "What is the current env? ${current_env} - $MY_ENV_VAR"
            echo "env.CURRENT_ENV ${{ env.CURRENT_ENV }}"
            echo "CURRENT_ENV $CURRENT_ENV"
          fi
      - name: Select environment
        id: select-environment
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then
            echo "dev"
            echo "selected-stage=dev" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "staging"
            echo "selected-stage=staging" >> "$GITHUB_OUTPUT"
          else
            echo "test"
            echo "selected-stage=test" >> "$GITHUB_OUTPUT"
          fi
                
      - name: Use conditional value - select-environment
        run: 'echo "${{ steps.select-environment.outputs.select-environment }}"'
      - name: >-
          Checkout ${{ github.head_ref }} - ${{ github.ref_name }} - ${{
          github.event.pull_request.base.ref }}
        env:
          PROJECT_ID2: 'accuwriter-${{ github.event.pull_request.base.ref }}'
          TEST_VAR3: 'lib/main\_${{ env.CURRENT_ENV }}'
          TEST_VAR4: 'lib/asd_${{ env.CURRENT_ENV }}'
          TEST_VAR5: 'lib/main_${{ env.CURRENT_ENV }}'
        run: >-
          echo 'Base_REF ${{ github.base_ref }} {TARGET} ${{ env.TARGET }}
          {TEST_VAR3} ${TEST_VAR3} TEST_VAR4 $TEST_VAR4 TEST_VAR5 $TEST_VAR5
          PROJECT_ID2 ${PROJECT_ID2}'
      - name: Checkout PROJECT_ID1
        env:
          PROJECT_ID1: 'accuwriter-${{ github.event.pull_request.base.ref }}'
        run: echo $PROJECT_ID1
      - name: Checkout PROJECT_ID
        run: echo $PROJECT_ID
      - name: Checkout PROJECT_ID
        run: echo 'PROJECT_ID_$PROJECT_ID'
      - name: Checkout TARGET env
        env:
          TARGET1: 'lib/main_${{ github.base_ref }}'
        run: echo $TARGET1
      - name: Checkout TARGET
        run: 'echo ''lib/main_${{ env.TARGET }}'''
      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.x
          channel: stable
          cache: true
      - name: Web Build
        run: >-
          flutter build web --dart-define --target ${{ env.TARGET }}
          --no-tree-shake-icons
