name: Dart (test)
'on':
  push:
    branches:
      - andersonbelli-patch-2
      - develop
      - master
env:
  QA: qa
  STAGING: staging
  DEV: develop
  MY_ENV_VAR: '${{ github.ref_name == ''develop'' }}'
  CURRENT_ENV: '${{ github.ref_name }}'
  PROJECT_ID: 'accuwriter-${{ github.ref_name }}'
  TARGET: 'lib/main_${{ github.ref_name }}.dart'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-cond@v1
        id: checkenv
        continue-on-error: true
        with:
          cond: '${{ github.ref_name == ''develop'' }}'
          if_true: $( echo 'my_dev_true' >> $CURRENT_ENV )
          if_false: $( echo 'my_dev_false' >> $CURRENT_ENV )
      - name: github.event.head_commit echo
        run: 'echo github_head_commit -> "${{ github.event.head_commit.message }}"'
      - name: bash echo
        run: 'myvar=$(echo "short stringa1234567" | sed "s/\(.\{15\}\).*/\1.../");'
      - name: bash echo myvar
        run: "echo $myvar"
      - name: Truncate String
        uses: 2428392/gh-truncate-string-action@v1.2.0
        id: truncatedString
        with:
          stringToTruncate: ${{ github.event.head_commit.message }}
          maxLength: 60
      - name: Truncate String echo
        run: 'echo truncatestring -> "${{ steps.truncatedString.outputs.string }}"'
      - name: aaaaaa
        run: 'echo -------------'
