name: Dart (test)
'on':
  push:
    branches:
      - andersonbelli-patch-2
      - develop
      - master
env:
  QA: qa
  STAGING: staging
  DEV: develop
  MY_ENV_VAR: '${{ github.ref_name == ''develop'' }}'
  CURRENT_ENV: '${{ github.ref_name }}'
  PROJECT_ID: 'accuwriter-${{ github.ref_name }}'
  TARGET: 'lib/main_${{ github.ref_name }}.dart'
jobs:
  envSetup:
    name: Publish Base Environment Vars
    runs-on: ubuntu-latest
    outputs:
      truncated: ${{ steps.truncated-str.outputs.truncated-commit }}
    steps:
      - name: truncate string
        shell: bash
        id: truncated-str
        run: echo "truncated-commit=${{ github.event.head_commit.message }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [envSetup]
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-cond@v1
        id: checkenv
        continue-on-error: true
        with:
          cond: '${{ github.ref_name == ''develop'' }}'
          if_true: $( echo 'my_dev_true' >> $CURRENT_ENV )
          if_false: $( echo 'my_dev_false' >> $CURRENT_ENV )
      - name: Truncate String
        id: truncate
        run: |
          str="${{ github.event.head_commit.message }}"
          if [ ${#str} -gt 30 ]; then
            truncatedStr=$(echo "$str" | cut -c -30)
          else
            truncatedStr="$str"
          fi
          echo "{truncated_string}={truncatedStr}" >> $GITHUB_OUTPUT
          echo "truncated_string: ${truncated_string}"

      - name: Use Truncated String
        run: |
          run: |
          echo "string: ${{ needs.EnvSetup.outputs.truncated }}"
        
