name: Dart (test)
'on':
  push:
    branches:
      - andersonbelli-patch-2
      - develop
      - master
env:
  QA: qa
  STAGING: staging
  DEV: develop
  MY_ENV_VAR: '${{ github.ref_name == ''develop'' }}'
  CURRENT_ENV: '${{ github.ref_name }}'
  PROJECT_ID: 'accuwriter-${{ github.ref_name }}'
  TARGET: 'lib/main_${{ github.ref_name }}.dart'
jobs:
  envSetup:
    name: Publish Base Environment Vars
    runs-on: ubuntu-latest
    outputs:
      truncated: ${{ steps.truncated-str.outputs.truncated-commit }}
    steps:
      - name: Truncate String
        id: truncated-str
        shell: bash
        run: |
          str="${{ github.event.head_commit.message }}"
          echo "str: ${str}"
          if [ ${#str} -gt 30 ]; then
            echo "if str: ${str}"
            truncatedStr=$(echo "$str" | cut -c -30)
            echo "if truncatedStr: ${truncatedStr}"
          else
            truncatedStr="$str"
            echo "else truncatedStr: ${truncatedStr}"
          fi
          echo "truncated_string: ${truncatedStr}"
          
          echo "truncated-commit=${truncatedStr}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [envSetup]
    steps:
      - name: Use Truncated String
        shell: bash
        run: |
          echo "string: ${{ needs.envSetup.outputs.truncated }}"
        
