name: Dart (test)
'on':
  push:
    branches:
      - andersonbelli-patch-2
      - develop
      - master
env:
  QA: qa
  STAGING: staging
  DEV: develop
  MY_ENV_VAR: '${{ github.ref_name == ''develop'' }}'
  CURRENT_ENV: '${{ github.ref_name }}'
  PROJECT_ID: 'accuwriter-${{ github.ref_name }}'
  TARGET: 'lib/main_${{ github.ref_name }}.dart'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.truncate.outputs.truncated_string }}
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-cond@v1
        id: checkenv
        continue-on-error: true
        with:
          cond: '${{ github.ref_name == ''develop'' }}'
          if_true: $( echo 'my_dev_true' >> $CURRENT_ENV )
          if_false: $( echo 'my_dev_false' >> $CURRENT_ENV )
      - name: Truncate String
        id: truncate
        run: |
          str="${{ github.event.head_commit.message }}"
          if [ ${#str} -gt 30 ]; then
            truncatedStr=$(echo "$str" | cut -c -30)
          else
            truncatedStr="$str"
          fi
          echo "{truncated_string}={truncatedStr}" >> $GITHUB_OUTPUT

      - name: Use Truncated String
        env:
          OUTPUT1: ${{steps.truncate.outputs.output1}}
        run: |
          echo "Truncated String: OUTPUT1: $OUTPUT1"
          echo "Truncated String: truncated: ${{ steps.truncate.outputs.truncated_string }}"
        
